language: python
python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
 - "3.10"
 - "3.11-dev"
 - "pypy"
 - "pypy3"
install:
 - pip install -q "flake8"
script:
 - nosetests --with-coverage --cover-package=statsd
 - flake8 statsd/
